sudo: false

language: scala
jdk:
  - oraclejdk8
  - openjdk11
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2/cache -name "*-SNAPSHOT*" -delete
